biomarker_groups:
  - ['FiO2', 'PaO2', 'PaCO2', 'SaO2', 'RespRate', 'pH', 'MechVent']
  - ['ALP']
  - ['ALT']
  - ['AST']
  - ['Albumin']
  - ['BUN']
  - ['Bilirubin']
  - ['Cholesterol']
  - ['Creatinine']
  - ['DiasABP']
  - ['GCS']
  - ['Glucose']
  - ['HCO3']
  - ['HCT']
  - ['HR']
  - ['K']
  - ['Lactate']
  - ['MAP']
  - ['Mg']
  - ['NIDiasABP']
  - ['NIMAP']
  - ['NISysABP']
  - ['Na']
  - ['Platelets']
  - ['SysABP']
  - ['Temp']
  - ['TroponinI']
  - ['TroponinT']
  - ['Urine']
  - ['WBC']