biomarker_groups:
  - ['Na', 'K', 'Mg', 'HCO3', 'Lactate', 'Glucose']
  - ['ALP']
  - ['ALT']
  - ['AST']
  - ['Albumin']
  - ['BUN']
  - ['Bilirubin']
  - ['Cholesterol']
  - ['Creatinine']
  - ['DiasABP']
  - ['FiO2']
  - ['GCS']
  - ['HCT']
  - ['HR']
  - ['MAP']
  - ['MechVent']
  - ['NIDiasABP']
  - ['NIMAP']
  - ['NISysABP']
  - ['PaCO2']
  - ['PaO2']
  - ['Platelets']
  - ['RespRate']
  - ['SaO2']
  - ['SysABP']
  - ['Temp']
  - ['TroponinI']
  - ['TroponinT']
  - ['Urine']
  - ['WBC']
  - ['pH']