biomarker_groups:
  - ['ALT', 'AST', 'ALP', 'Albumin', 'Bilirubin', 'Cholesterol']
  - ['BUN']
  - ['Creatinine']
  - ['DiasABP']
  - ['FiO2']
  - ['GCS']
  - ['Glucose']
  - ['HCO3']
  - ['HCT']
  - ['HR']
  - ['K']
  - ['Lactate']
  - ['MAP']
  - ['MechVent']
  - ['Mg']
  - ['NIDiasABP']
  - ['NIMAP']
  - ['NISysABP']
  - ['Na']
  - ['PaCO2']
  - ['PaO2']
  - ['Platelets']
  - ['RespRate']
  - ['SaO2']
  - ['SysABP']
  - ['Temp']
  - ['TroponinI']
  - ['TroponinT']
  - ['Urine']
  - ['WBC']
  - ['pH']