biomarker_groups:
  - ['HR', 'MAP', 'SysABP', 'DiasABP', 'NIMAP', 'NISysABP', 'NIDiasABP']
  - ['ALP']
  - ['ALT']
  - ['AST']
  - ['Albumin']
  - ['BUN']
  - ['Bilirubin']
  - ['Cholesterol']
  - ['Creatinine']
  - ['FiO2']
  - ['GCS']
  - ['Glucose']
  - ['HCO3']
  - ['HCT']
  - ['K']
  - ['Lactate']
  - ['MechVent']
  - ['Mg']
  - ['Na']
  - ['PaCO2']
  - ['PaO2']
  - ['Platelets']
  - ['RespRate']
  - ['SaO2']
  - ['Temp']
  - ['TroponinI']
  - ['TroponinT']
  - ['Urine']
  - ['WBC']
  - ['pH']